# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
jobs:
- job: DEVEUW
  displayName: DEV-EUW
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: git://Global Tax Platform/Configuration
    clean: true
    persistCredentials: true
  - task: PowerShell@2 
    inputs:
      targetType: 'inline'
      script: 'Get-ChildItem $(System.DefaultWorkingDirectory) -Recurse;'
      failOnStderr: true
      workingDirectory: '$(System.DefaultWorkingDirectory)'
