Push-Location "C:\EYdev\devops\pipelines";
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Release 9.5\*') -WhatIf;
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Release 9.5\persistenceservices-ctp-R9.5');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Release 9.5\1 - user-db-ctp-R9.5');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\apaccit-clientconfig-db-ctp');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Global Tax Platform - App - APIM - Portal (ctp)');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\deliverableservice-ctp');
#@('\CTP\Release 7.2\*','\CTP\Release 7.5\*') | Remove-UnneededReleases -WhatIf;
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Release 8.2\*');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Release 8.4\*');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Release 9.1\*');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Release 9.2\*');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Release 9.3\*');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Release 9.4\*');
Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Release 9.5\*');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Release 10.2\*');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Through Dev-QA\*');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Through UAT-Perf\*');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\*');
#Remove-UnneededReleases -ReleaseDefinitions @('\CTP\Release 9.5\00 - APIM Release-ctp-R9.5');
Pop-Location;
